apiVersion: 1

datasources:
  - name: bfs2y0169i2v4b
    uid: bfs2y0169i2v4b
    type: mssql
    access: proxy
    url: sqlserver:1433
    user: sa
    secureJsonData:
      password: "SqlServer2026!"
    jsonData:
      database: TestDB
      sslmode: disable
      encrypt: disable
    isDefault: true
    editable: true
